In [ ]:
import re

import pandas as pd

targetCSV = "CSV/imdb_episodes.csv"

In [9]:
df = pd.read_csv(targetCSV)
df

,Slug,Title,Description,Rating,Rating Count,Duration,Release Date,Genres,Poster
0,tt0035599,Voice of Firestone Televues,Documentary films on diverse subjects.,NaN,NaN,NaN,1943-11-29,NaN,NaN
1,tt15340888,Lady Napoleon,"Sophie, descendant of Napoleon, leads Lady Nap...",NaN,NaN,NaN,NaN,"['Animation', 'Action', 'Adventure']",imdb_episode_images\Lady_Napoleon.jpg
2,tt27658590,MañanaEsTooLate con Lorenzo Parro,A comedy show that serves up the funniest and ...,NaN,NaN,NaN,2020-04-07,['Comedy'],imdb_episode_images\MañanaEsTooLate_con_Lorenz...
3,tt10515284,D_Sawz Tv,NaN,NaN,NaN,NaN,2016-09-03,['Comedy'],imdb_episode_images\D_Sawz_Tv.jpg
4,tt4816058,Dragons: Race to the Edge,Unlock the secrets of the Dragon Eye and come ...,8.2,9308.0,NaN,2015-06-26,"['Animation', 'Action', 'Adventure']",imdb_episode_images\Dragons_Race_to_the_Edge.jpg
...,...,...,...,...,...,...,...,...,...
99099,tt6408200,The Greater America&apos;s Phobia Support Grou...,The Members of the Greater America&apos;s Phob...,NaN,NaN,NaN,2016-12-23,['Comedy'],imdb_episode_images\The_Greater_Americaaposs_P...
99100,tt6442346,Sarangeun Amuna Hana,A comedy drama centering around 4 sisters. The...,NaN,NaN,NaN,2009-03-08,"['Comedy', 'Drama', 'Romance']",imdb_episode_images\Sarangeun_Amuna_Hana.jpg
99101,tt11994256,Ykkösaamu,The &quot;sister show&quot; of the radio progr...,4.4,9.0,NaN,2008-09-13,['Talk-Show'],imdb_episode_images\Ykkösaamu.jpg
99102,tt0288359,The Frost Programme,NaN,NaN,NaN,NaN,1977-06-02,['Talk-Show'],NaN
99103,tt11994996,The Fake Spaniards Show,The Fake Spaniards are a group of characters k...,NaN,NaN,NaN,2010-11-23,['Comedy'],imdb_episode_images\The_Fake_Spaniards_Show.jpg

In [10]:
df['Poster']

0                                                      NaN
1                    imdb_episode_images\Lady_Napoleon.jpg
2        imdb_episode_images\MañanaEsTooLate_con_Lorenz...
3                        imdb_episode_images\D_Sawz_Tv.jpg
4         imdb_episode_images\Dragons_Race_to_the_Edge.jpg
                               ...
99099    imdb_episode_images\The_Greater_Americaaposs_P...
99100         imdb_episode_images\Sarangeun_Amuna_Hana.jpg
99101                    imdb_episode_images\Ykkösaamu.jpg
99102                                                  NaN
99103      imdb_episode_images\The_Fake_Spaniards_Show.jpg
Name: Poster, Length: 99104, dtype: object

In [11]:
# Modify the poster column to use snake case format instead of the normal one with spaces.

def snake_case(s):
	print(s)
	if str(s) == "nan":
		return s
	return re.sub(r'\s+', '_', s)

df['Poster'] = df['Poster'].apply(snake_case)
df

nan
imdb_episode_images\Lady_Napoleon.jpg
imdb_episode_images\MañanaEsTooLate_con_Lorenzo_Parro.jpg
imdb_episode_images\D_Sawz_Tv.jpg
imdb_episode_images\Dragons_Race_to_the_Edge.jpg
nan
imdb_episode_images\Die_Deutsche_Wochenschau.jpg
imdb_episode_images\Mamma_Mia_I_Have_a_Dream.jpg
nan
imdb_episode_images\Mer_panik_i_tomteverkstan.jpg
nan
imdb_episode_images\Breaking_Ground.jpg
imdb_episode_images\Dancing_Fools.jpg
imdb_episode_images\BattleBots.jpg
imdb_episode_images\Helpsters.jpg
nan
imdb_episode_images\Jeonjijeok_Chamgyeon_Sijeom.jpg
imdb_episode_images\Natureaposs_Greatest_Dancers.jpg
imdb_episode_images\Irish_Pictorial_Weekly.jpg
imdb_episode_images\Dong_wu_guan_li_ju.jpg
imdb_episode_images\Dabba_Cartel.jpg
nan
imdb_episode_images\Pejling.jpg
imdb_episode_images\If_Iaposm_Alive_Next_Week.jpg
imdb_episode_images\Outsiders.jpg
imdb_episode_images\Une_mère_parfaite.jpg
imdb_episode_images\Kraft_Television_Theatre.jpg
imdb_episode_images\Faktor_strakha.jpg
imdb_episode_images\Quinta_Categoria.jpg
imdb_episode_images\Coded.jpg
imdb_episode_images\Shtorm.jpg
nan
imdb_episode_images\Marshalaposs_Law.jpg
imdb_episode_images\Dokument_utifrån.jpg
imdb_episode_images\The_Croods_Family_Tree.jpg
imdb_episode_images\Public_Prosecutor.jpg
imdb_episode_images\Laposinvité.jpg
imdb_episode_images\Procureurs.jpg
imdb_episode_images\Fence.jpg
imdb_episode_images\Fighting_Youth.jpg
nan
imdb_episode_images\Actoraposs_Studio.jpg
nan
imdb_episode_images\Inuyasha_Kanketsu-hen.jpg
nan
imdb_episode_images\The_Crystal_Maze.jpg
imdb_episode_images\Nastoyashaya_Vanga.jpg
imdb_episode_images\Decameron_di_Daniele_Luttazzi.jpg
imdb_episode_images\Darüber_staunt_die_Welt.jpg
nan
imdb_episode_images\Singled_Out.jpg
imdb_episode_images\Neoreul_Saranghan_Shigan.jpg
imdb_episode_images\Összezárva_Hajdú_Péterrel.jpg
imdb_episode_images\Made_Up_in_Belfast.jpg
imdb_episode_images\The_Arrow_Show.jpg
nan
nan
imdb_episode_images\Curse_of_Akakor.jpg
imdb_episode_images\The_Vineyard.jpg
imdb_episode_images\Propavshie_Poslednyaya_nadezhda.jpg
imdb_episode_images\Talent_Scouts.jpg
imdb_episode_images\Aileler_Yarisiyor.jpg
nan
imdb_episode_images\Ask_101.jpg
nan
imdb_episode_images\Más_que_Sexo.jpg
imdb_episode_images\Casey_Neistat_Vlog.jpg
imdb_episode_images\Beauty_7.jpg
imdb_episode_images\New_Mexico_Rising.jpg
nan
nan
nan
imdb_episode_images\La_CQ.jpg
nan
nan
nan
imdb_episode_images\Chip_aposnapos_Dale_Park_Life.jpg
imdb_episode_images\Bogatye_i_znamenitye.jpg
imdb_episode_images\Break_the_Bank.jpg
nan
imdb_episode_images\Dilemas_de_Irene.jpg
nan
imdb_episode_images\Candid_Camera.jpg
imdb_episode_images\Les_aventures_de_Babar.jpg
imdb_episode_images\Flaming_Screens.jpg
imdb_episode_images\The_Dirty_Stars.jpg
imdb_episode_images\Aitana_las_dos_caras_de_un_fenómeno.jpg
nan
imdb_episode_images\Pie_Boy.jpg
imdb_episode_images\Mazed_Tales.jpg
nan
nan
nan
imdb_episode_images\The_Chevrolet_Tele-Theatre.jpg
imdb_episode_images\100_mexicanos_dijieron.jpg
imdb_episode_images\Sticky.jpg
nan
imdb_episode_images\Life_and_Birth.jpg
nan
imdb_episode_images\Pre_Drinks.jpg
imdb_episode_images\Pet_Intervention.jpg
nan
imdb_episode_images\Office_Ladies_Animated_Series.jpg
imdb_episode_images\Worzel_Gummidge.jpg
nan
nan
imdb_episode_images\Celebrity_House_Cleaner.jpg
nan
imdb_episode_images\PINY_Institute_of_New_York.jpg
nan
imdb_episode_images\Kesäkuski.jpg
imdb_episode_images\The_Voice_of_Germany_Rap.jpg
imdb_episode_images\Euskolegas.jpg
imdb_episode_images\Texaco_Star_Theatre_Starring_Milton_Berle.jpg
imdb_episode_images\Dosti_Yaariyan_Manmarziyan.jpg
imdb_episode_images\Dannyaposs_House.jpg
imdb_episode_images\Como_la_Vida_Misma.jpg
imdb_episode_images\Ezel.jpg
imdb_episode_images\The_Morey_Amsterdam_Show.jpg
imdb_episode_images\Beachcomber_Bay.jpg
imdb_episode_images\Female_Friendly.jpg
imdb_episode_images\Masterchef_Australia_The_Professionals.jpg
imdb_episode_images\Fabulocity.jpg
nan
imdb_episode_images\Punta_Escarlata.jpg
imdb_episode_images\PL_Boz.jpg
imdb_episode_images\Behind_the_Feed.jpg
nan
imdb_episode_images\Qué_vida_más_triste.jpg
imdb_episode_images\Our_Boys.jpg
imdb_episode_images\Active_Living.jpg
imdb_episode_images\Tellement_Gay_Homosexualité_et_pop_culture.jpg
nan
nan
nan
nan
imdb_episode_images\23_pares.jpg
imdb_episode_images\Fängelseexperimentet_Little_Scandinavia.jpg
nan
imdb_episode_images\Los_protegidos.jpg
nan
nan
imdb_episode_images\The_Perry_Como_Show.jpg
imdb_episode_images\Borgarstjórinn.jpg
imdb_episode_images\Motivational_Hypnotherapy.jpg
nan
imdb_episode_images\Celebrity_Hunted_Chasse_à_laposhomme.jpg
imdb_episode_images\The_Philco_Television_Playhouse.jpg
imdb_episode_images\Donapost_Blink.jpg
nan
imdb_episode_images\Plevako.jpg
imdb_episode_images\Batman_Unlimited.jpg
nan
imdb_episode_images\Remember_You.jpg
imdb_episode_images\The_Sex_Game.jpg
imdb_episode_images\Shit_Creek.jpg
imdb_episode_images\Los_Angelesin_kuningas.jpg
imdb_episode_images\The_Experience_of_Kairo_and_Crate.jpg
nan
imdb_episode_images\Studio_One.jpg
imdb_episode_images\Kuhl_amp_Kultig.jpg
imdb_episode_images\Junk_Mail.jpg
imdb_episode_images\Blokhuis_Extra_De_Jaren_80.jpg
nan
imdb_episode_images\Snapping_Show.jpg
imdb_episode_images\Mooie_Mensen.jpg
imdb_episode_images\Lac-Mégantic_-_ceci_naposest_pas_un_accident.jpg
imdb_episode_images\Temple_Baptist_Church_Live_Webcast.jpg
nan
imdb_episode_images\Toast_of_the_Town.jpg
nan
nan
imdb_episode_images\Ocean_Action_Reports.jpg
nan
imdb_episode_images\Baby_Sharkaposs_Big_Show.jpg
nan
nan
imdb_episode_images\Belaya_studiya.jpg
nan
imdb_episode_images\Dirty_Love.jpg
imdb_episode_images\Marsra_magyar.jpg
nan
imdb_episode_images\We_the_People.jpg
imdb_episode_images\Tu_Mera_Hero.jpg
imdb_episode_images\Fascinating_New_Zealand.jpg
imdb_episode_images\Eaux_Turbulentes.jpg
imdb_episode_images\KEPS_Cozy_Mysteries.jpg
nan
imdb_episode_images\Chelovek_v_kadre.jpg
imdb_episode_images\Bitch_X_Rich.jpg
imdb_episode_images\Rojo_Verano.jpg
imdb_episode_images\A_Little_Bit.jpg
imdb_episode_images\Toto_Nêchan.jpg
imdb_episode_images\The_Admiral_Broadway_Revue.jpg
imdb_episode_images\Tecno_Phantom_V_Fold.jpg
nan
nan
imdb_episode_images\House_of_Drag.jpg
imdb_episode_images\Hot_Ass_Messes_HAM.jpg
imdb_episode_images\Adulting.jpg
nan
imdb_episode_images\Al_Morgan.jpg
imdb_episode_images\Kids_Rule_with_Kyler_and_Mad.jpg
imdb_episode_images\Lessons_from_the_Grave.jpg
nan
imdb_episode_images\Conde_Vrolok.jpg
nan
imdb_episode_images\The_Aldrich_Family.jpg
imdb_episode_images\Boukia_kai_syhorio.jpg
imdb_episode_images\Siren_Survive_the_Island.jpg
imdb_episode_images\Jeev_Majha_Guntala.jpg
nan
nan
imdb_episode_images\Ilha_das_Cores.jpg
nan
imdb_episode_images\Extreme.jpg
imdb_episode_images\Very_Special.jpg
nan
imdb_episode_images\Dr_Xaposs_Cinemondo.jpg
imdb_episode_images\To_kouti_tis_Pandoras.jpg
imdb_episode_images\Hollyscoop.jpg
imdb_episode_images\Paredão_dos_Famosos.jpg
imdb_episode_images\Whereaposs_the_Love.jpg
imdb_episode_images\Arthur_Godfrey_and_His_Friends.jpg
imdb_episode_images\Side_Hustlers.jpg
imdb_episode_images\NurdRage.jpg
imdb_episode_images\World_War_Two.jpg
imdb_episode_images\Selling_Yachts.jpg
nan
imdb_episode_images\Dirt_The_Last_Great_American_Sport.jpg
imdb_episode_images\Jane_Pratt.jpg
imdb_episode_images\Destination_Hollywood.jpg
nan
imdb_episode_images\Mstitel_Strashnyy_les.jpg
nan
imdb_episode_images\Tonaka_Files.jpg
imdb_episode_images\U-Prince_The_Extroverted_Humanist.jpg
imdb_episode_images\Hoch_Hinaus_-_Das_Expeditionsteam.jpg
imdb_episode_images\Ride_the_Rock.jpg
nan
imdb_episode_images\Believe_It_or_Not.jpg
imdb_episode_images\Kitty_911.jpg
imdb_episode_images\MsLabelled.jpg
imdb_episode_images\Ludi_kamen.jpg
nan
imdb_episode_images\Tiny_Furries.jpg
nan
imdb_episode_images\The_Philosophy_of_Crypto.jpg
imdb_episode_images\4Jim.jpg
imdb_episode_images\The_Big_Story.jpg
imdb_episode_images\Paripi_Koumei.jpg
imdb_episode_images\The_50_Greatest_Moments_at_Madison_Square_Garden.jpg
nan
imdb_episode_images\just2good_Original_Subreddit_Show.jpg
nan
imdb_episode_images\Laura_Whitmoreaposs_Breakfast_Show.jpg
imdb_episode_images\Gratitude_UnFiltered_ReMixed.jpg
imdb_episode_images\Aoki_ryûsei_SPT_Reizunâ.jpg
nan
imdb_episode_images\The_Spinoffs.jpg
imdb_episode_images\Khaen_Rak_Salap_Chata.jpg
nan
nan
nan
imdb_episode_images\The_Disney_Channel_Games.jpg
imdb_episode_images\Kljun.jpg
nan
nan
imdb_episode_images\Unter_Deutschen_-_Zwangsarbeit_im_NS-Staat.jpg
imdb_episode_images\Dr_Steve-O.jpg
imdb_episode_images\Captain_Video_and_His_Video_Rangers.jpg
imdb_episode_images\Channel_Zero.jpg
imdb_episode_images\Rune_Klans_trylleshow_-_hokus_fucking_pokus.jpg
imdb_episode_images\Oti_Mabuseaposs_Breakfast_Show.jpg
imdb_episode_images\The_Many_Adventures_of_Mr_Mailman.jpg
imdb_episode_images\Cavalcade_of_Stars.jpg
imdb_episode_images\Shadows_of_the_Plague.jpg
imdb_episode_images\Likit_Ruk_Karm_Duang_Dao.jpg
imdb_episode_images\Folk.jpg
imdb_episode_images\Missing_Persons_Unit.jpg
imdb_episode_images\Celebrity_Time.jpg
imdb_episode_images\Paolo_Rumiz_racconta_la_grande_guerra.jpg
imdb_episode_images\House_of_Monsters.jpg
nan
nan
imdb_episode_images\The_Contender_Australia.jpg
imdb_episode_images\Montana_Jones.jpg
imdb_episode_images\Il_Cammino_dellaposAppia_Antica.jpg
imdb_episode_images\Land_of_the_Outlaws.jpg
nan
imdb_episode_images\The_Morning_Show_with_Mike_amp_Juliet.jpg
imdb_episode_images\Influencers_Sobrevivir_a_las_redes.jpg
imdb_episode_images\Lucid_Technica.jpg
nan
nan
nan
imdb_episode_images\NewNowNext_Music.jpg
imdb_episode_images\What_Really_Happens_in_Bali.jpg
imdb_episode_images\The_Hook_Down.jpg
imdb_episode_images\The_Ed_Wynn_Show.jpg
imdb_episode_images\Unfiltered_Minds.jpg
nan
nan
imdb_episode_images\The_art_of_of_discovery.jpg
imdb_episode_images\The_Fifty-Fourth_Street_Revue.jpg
nan
imdb_episode_images\Velikaya_voyna.jpg
imdb_episode_images\Avenue_B.jpg
imdb_episode_images\WWF_Action_Zone.jpg
imdb_episode_images\Fireside_Theatre.jpg
imdb_episode_images\The_Silent_Civil_War.jpg
nan
imdb_episode_images\We_Are_New_York.jpg
nan
imdb_episode_images\The_Ford_Television_Theatre.jpg
imdb_episode_images\Playing_Fields.jpg
nan
imdb_episode_images\No_Chill_with_Gilbert_Arenas.jpg
imdb_episode_images\True_Pulp_Murder.jpg
nan
imdb_episode_images\Algo_habrán_hecho.jpg
imdb_episode_images\Fairy_Book_Club.jpg
nan
nan
imdb_episode_images\Indivisible.jpg
imdb_episode_images\Nunmuleui_yeowang.jpg
imdb_episode_images\Bolshie_roditeli.jpg
imdb_episode_images\The_Nines.jpg
imdb_episode_images\Honeymoon_Savdhaan.jpg
imdb_episode_images\The_Goldbergs.jpg
imdb_episode_images\Divino_tesoro.jpg
imdb_episode_images\Idol.jpg
nan
nan
imdb_episode_images\Mullét_Heights.jpg
imdb_episode_images\On_the_Money_with_RJ_Atkins.jpg
imdb_episode_images\Turkstar.jpg
imdb_episode_images\17_klostes.jpg
nan
imdb_episode_images\The_Tyler_Perry_Show.jpg
imdb_episode_images\Nya_Arga_snickaren.jpg
imdb_episode_images\Doctor_Barry.jpg
imdb_episode_images\All_Fire_No_Mids.jpg
imdb_episode_images\All_About_Jack.jpg
imdb_episode_images\Hopalong_Cassidy.jpg
nan
imdb_episode_images\Media_Empire.jpg
imdb_episode_images\Amrapali.jpg
imdb_episode_images\The_Black_Dawn.jpg
imdb_episode_images\Inside_USA_with_Chevrolet.jpg
imdb_episode_images\Confessions_of_a_Hollywood_Bartender.jpg
imdb_episode_images\Controlled_Chaos.jpg
imdb_episode_images\Charamyog.jpg
imdb_episode_images\Jack_Leonard.jpg
imdb_episode_images\Dallas_Divas_amp_Daughters.jpg
nan
imdb_episode_images\Funny_Brown_People.jpg
nan
nan
imdb_episode_images\Shadyantra.jpg
imdb_episode_images\The_Drunken_Peasants.jpg
nan
imdb_episode_images\Dil_Hai_Chota_Sa_Choti_Si_Asha.jpg
imdb_episode_images\Luna_Park.jpg
imdb_episode_images\This_Is_Paradise.jpg
nan
imdb_episode_images\The_Life_of_Riley.jpg
imdb_episode_images\Saripa.jpg
imdb_episode_images\The_Divine_Comedy_Inferno_Purgatory_and_Paradise.jpg
imdb_episode_images\Familia_Moderna.jpg
imdb_episode_images\Iconic_Records_S01__the_Notorious_BIG.jpg
nan
imdb_episode_images\Lights_Out.jpg
imdb_episode_images\ALZhIR.jpg
imdb_episode_images\Ludere_lommetyve_og_lirekassemænd.jpg
imdb_episode_images\Horrified.jpg
nan
imdb_episode_images\The_Lone_Ranger.jpg
imdb_episode_images\Punkaposd.jpg
imdb_episode_images\The_Jump.jpg
imdb_episode_images\The_Sorrow.jpg
imdb_episode_images\Toute_la_vérité.jpg
nan
imdb_episode_images\Mama.jpg
nan
imdb_episode_images\The_Last_Cowboy.jpg
imdb_episode_images\Trauma.jpg
imdb_episode_images\Man_Against_Crime.jpg
nan
nan
imdb_episode_images\Cheerleaders.jpg
imdb_episode_images\Cosmo_Whispers_ASMR.jpg
imdb_episode_images\Yamaska.jpg
nan
imdb_episode_images\Kirisute_Gomen.jpg
imdb_episode_images\Martin_Kane_Private_Eye.jpg
imdb_episode_images\Mathagam.jpg
nan
imdb_episode_images\Ciclo_de_teatro_argentino.jpg
imdb_episode_images\Wide_Scream_Theatre.jpg
imdb_episode_images\Between_Two_Ferns_with_Zach_Galifianakis.jpg
imdb_episode_images\David_Hoffman.jpg
imdb_episode_images\Mr_I_Magination.jpg
imdb_episode_images\Ulan_Istanbul.jpg
imdb_episode_images\Dr_Cadaveraposs_Monster_Horror_Theatre.jpg
imdb_episode_images\Terapia_Alternativa.jpg
imdb_episode_images\Todo_es_uno.jpg
nan
nan
imdb_episode_images\Extreme_Engagement.jpg
imdb_episode_images\Generation_911.jpg
nan
imdb_episode_images\The_Exchange.jpg
imdb_episode_images\Farm_Rebellion.jpg
nan
imdb_episode_images\Alien_Skies.jpg
imdb_episode_images\Arch_Oboleraposs_Comedy_Theatre.jpg
imdb_episode_images\La_Fabrica_del_Deseo.jpg
nan
imdb_episode_images\Banat_Kharqat_Banat_Superman.jpg
imdb_episode_images\One_Manaposs_Family.jpg
imdb_episode_images\Munich_Games.jpg
imdb_episode_images\Ruset.jpg
imdb_episode_images\Terminator_Genisys_The_YouTube_Chronicles.jpg
imdb_episode_images\Wig_Out.jpg
imdb_episode_images\The_Paul_Whitemanaposs_Goodyear_Revue.jpg
imdb_episode_images\Tracy_Beaker_Returns.jpg
imdb_episode_images\Chiller_Night_Theater.jpg
imdb_episode_images\True_Tunes.jpg
imdb_episode_images\Operación_Barrio_Inglés.jpg
imdb_episode_images\The_Ruggles.jpg
nan
imdb_episode_images\Kuhinje_svijeta.jpg
imdb_episode_images\English_Premier_League_20042005.jpg
nan
nan
nan
imdb_episode_images\The_Ortega_Show.jpg
imdb_episode_images\English_Premier_League_20062007.jpg
imdb_episode_images\Star_Wars_Captain_Phasma.jpg
imdb_episode_images\The_Silver_Theatre.jpg
imdb_episode_images\Jack_Shadowaposs_Chiller_Night_Presents.jpg
imdb_episode_images\La_forastera.jpg
imdb_episode_images\Blekingegade.jpg
imdb_episode_images\Giacomo_Leopardi-_il_poeta_infinito.jpg
nan
imdb_episode_images\Berg_och_Meltzer_i_Amerika.jpg
imdb_episode_images\English_Premier_League_20072008.jpg
nan
imdb_episode_images\Sew_Fierce.jpg
nan
imdb_episode_images\Curious_and_Unusual_Deaths.jpg
imdb_episode_images\Aço_es_un_destarifo.jpg
nan
imdb_episode_images\Escaping_Evil_My_Life_in_a_Cult.jpg
imdb_episode_images\Sleepy_Hollow_Theater.jpg
imdb_episode_images\Lop_Hoc_Vui_Nhon.jpg
imdb_episode_images\Three_Pines.jpg
nan
imdb_episode_images\Mafia_Spies.jpg
imdb_episode_images\Glavnye_lyudi.jpg
imdb_episode_images\Rotterdam_Ongehoord.jpg
imdb_episode_images\Brúðkaupið_mitt.jpg
imdb_episode_images\Erik_och_Mackan_gör_Kentucky.jpg
nan
imdb_episode_images\Game_of_Kook.jpg
nan
imdb_episode_images\Cuineres_i_cuiners.jpg
nan
imdb_episode_images\Eddy_and_the_Bear.jpg
imdb_episode_images\Renze_op_zondag.jpg
imdb_episode_images\Super_Circus.jpg
imdb_episode_images\Fûjin_no_Mon.jpg
imdb_episode_images\Chuzhoe_gnezdo.jpg
imdb_episode_images\First_Dates.jpg
imdb_episode_images\Brian_Ross_Investigates.jpg
imdb_episode_images\The_George_Lucas_Talk_Show_Stage_Show.jpg
nan
imdb_episode_images\Suspense.jpg
imdb_episode_images\Löwenbrüder.jpg
imdb_episode_images\Hwanggeumjeongwon.jpg
imdb_episode_images\Red_Bull_Storm_Chase.jpg
nan
imdb_episode_images\TV_Teen_Club.jpg
imdb_episode_images\Loteria_Loca.jpg
imdb_episode_images\English_Premier_League_20082009.jpg
imdb_episode_images\SuperHero_Diaries.jpg
nan
imdb_episode_images\Sean_Hughesapos_Inside_Tracks.jpg
nan
nan
nan
nan
imdb_episode_images\Golden_Blood.jpg
imdb_episode_images\Donal_MacIntyreaposs_Killer_Evidence.jpg
imdb_episode_images\This_Is_Show_Business.jpg
imdb_episode_images\Communities_of_the_Games.jpg
nan
imdb_episode_images\Bolshoy_pobeg.jpg
nan
nan
imdb_episode_images\Secrets_of_the_Underground.jpg
nan
imdb_episode_images\HGTV_Insider.jpg
imdb_episode_images\Tuning_In.jpg
imdb_episode_images\This_Is_a_Lot.jpg
imdb_episode_images\Thoughts_from_LA_2_the_UK.jpg
imdb_episode_images\Dangerous_Woman_Tour_Stage_Visual.jpg
imdb_episode_images\Versatile_Varieties.jpg
imdb_episode_images\No_Fuks_2_Give.jpg
nan
nan
imdb_episode_images\The_Voice_of_Firestone.jpg
imdb_episode_images\20_seiki_awâ.jpg
nan
nan
imdb_episode_images\Tujhse_Naraaz_Nahi_Zindagi.jpg
imdb_episode_images\Volume_One.jpg
imdb_episode_images\Perception_or_Reality.jpg
imdb_episode_images\The_Drawfee_Variety_Hour.jpg
imdb_episode_images\Relative_Justice.jpg
nan
imdb_episode_images\Atua_ou_Surta.jpg
imdb_episode_images\Between_the_Lines_Pretty_Lake_High_-_Yearbook_Assignment.jpg
imdb_episode_images\Bigger.jpg
imdb_episode_images\Paranormal_Egypt.jpg
imdb_episode_images\The_Wendy_Barrie_Show.jpg
nan
imdb_episode_images\Fuga_Impossível.jpg
imdb_episode_images\Tomorrowaposs_Hope.jpg
nan
nan
imdb_episode_images\The_Fabulous_Show_with_Fay_and_Fluffy.jpg
imdb_episode_images\Nomade_7.jpg
imdb_episode_images\Steel_River.jpg
nan
imdb_episode_images\Your_Show_Time.jpg
imdb_episode_images\Live_and_Unleashed_with_the_Dingo.jpg
imdb_episode_images\WolfMan.jpg
nan
nan
imdb_episode_images\Limited_Liability.jpg
nan
nan
imdb_episode_images\Anamika.jpg
imdb_episode_images\Youth_on_the_March.jpg
imdb_episode_images\Melting_Cheese.jpg
imdb_episode_images\Eliaposs_Places.jpg
imdb_episode_images\Unlikely_Cyphers.jpg
imdb_episode_images\This_Life.jpg
nan
imdb_episode_images\Nameless_Nomad_ASMR.jpg
imdb_episode_images\It_The_Animated_Series.jpg
imdb_episode_images\Wai_po_de_xin_shi_jie.jpg
nan
imdb_episode_images\The_Adventures_of_Ellery_Queen.jpg
imdb_episode_images\É_Ouro_O_Brilho_do_Brasil_em_Tóquio.jpg
imdb_episode_images\Tian_xiao_jie_yu_leng_xian_sheng.jpg
imdb_episode_images\Estambul.jpg
imdb_episode_images\Back_to_Field.jpg
imdb_episode_images\Quantum_Girl.jpg
imdb_episode_images\The_Alan_Young_Show.jpg
imdb_episode_images\Never_Out_of_Reach.jpg
nan
imdb_episode_images\Front_Row_Flynn.jpg
nan
imdb_episode_images\The_Dab_Roast_2021.jpg
imdb_episode_images\The_Tara_Sharma_Show.jpg
imdb_episode_images\Blue_Moon.jpg
nan
imdb_episode_images\Amores_Monumentales.jpg
imdb_episode_images\The_Basement.jpg
imdb_episode_images\A_Day_Turns_Daark.jpg
nan
imdb_episode_images\Summer_Love.jpg
imdb_episode_images\Armstrong_Circle_Theatre.jpg
imdb_episode_images\A_Sogra_Que_Te_Pariu.jpg
nan
nan
imdb_episode_images\Mother_Funders.jpg
imdb_episode_images\The_Next_Big_Thing.jpg
imdb_episode_images\Ritual.jpg
imdb_episode_images\The_Big_Clean_Up.jpg
nan
imdb_episode_images\The_Arthur_Murray_Party.jpg
imdb_episode_images\Never_After.jpg
nan
imdb_episode_images\Young_Single_and_Black.jpg
imdb_episode_images\Dare_to_Wear.jpg
imdb_episode_images\Beat_the_Clock.jpg
imdb_episode_images\Haramlek.jpg
imdb_episode_images\The_Seed_of_Love.jpg
nan
imdb_episode_images\Sheldon_Mashuganaaposs_Wacky_Adventures.jpg
imdb_episode_images\Resibo.jpg
imdb_episode_images\Beulah.jpg
nan
imdb_episode_images\Marmadesam_Vidaathu_Karuppu.jpg
imdb_episode_images\Heike_monogatari.jpg
imdb_episode_images\Jalan_Lain.jpg
imdb_episode_images\Big_Top.jpg
imdb_episode_images\Orkadia.jpg
imdb_episode_images\Stalingrad_Pobeda_izmenivshaya_mir.jpg
imdb_episode_images\Shi_Jie_Wei_Cheng_Li.jpg
nan
nan
imdb_episode_images\University_of_Andy.jpg
imdb_episode_images\Big_Town.jpg
imdb_episode_images\Ôbâteiku.jpg
nan
imdb_episode_images\Abu_Janti_1.jpg
imdb_episode_images\Tab-o_Tab.jpg
imdb_episode_images\Latterlig_politikk.jpg
imdb_episode_images\The_Bigelow_Theatre.jpg
nan
nan
imdb_episode_images\Hungama_Music_Bus.jpg
imdb_episode_images\The_Billy_Rose_Show.jpg
imdb_episode_images\Shahbaz.jpg

,Slug,Title,Description,Rating,Rating Count,Duration,Release Date,Genres,Poster
0,tt0035599,Voice of Firestone Televues,Documentary films on diverse subjects.,NaN,NaN,NaN,1943-11-29,NaN,NaN
1,tt15340888,Lady Napoleon,"Sophie, descendant of Napoleon, leads Lady Nap...",NaN,NaN,NaN,NaN,"['Animation', 'Action', 'Adventure']",imdb_episode_images\Lady_Napoleon.jpg
2,tt27658590,MañanaEsTooLate con Lorenzo Parro,A comedy show that serves up the funniest and ...,NaN,NaN,NaN,2020-04-07,['Comedy'],imdb_episode_images\MañanaEsTooLate_con_Lorenz...
3,tt10515284,D_Sawz Tv,NaN,NaN,NaN,NaN,2016-09-03,['Comedy'],imdb_episode_images\D_Sawz_Tv.jpg
4,tt4816058,Dragons: Race to the Edge,Unlock the secrets of the Dragon Eye and come ...,8.2,9308.0,NaN,2015-06-26,"['Animation', 'Action', 'Adventure']",imdb_episode_images\Dragons_Race_to_the_Edge.jpg
...,...,...,...,...,...,...,...,...,...
99099,tt6408200,The Greater America&apos;s Phobia Support Grou...,The Members of the Greater America&apos;s Phob...,NaN,NaN,NaN,2016-12-23,['Comedy'],imdb_episode_images\The_Greater_Americaaposs_P...
99100,tt6442346,Sarangeun Amuna Hana,A comedy drama centering around 4 sisters. The...,NaN,NaN,NaN,2009-03-08,"['Comedy', 'Drama', 'Romance']",imdb_episode_images\Sarangeun_Amuna_Hana.jpg
99101,tt11994256,Ykkösaamu,The &quot;sister show&quot; of the radio progr...,4.4,9.0,NaN,2008-09-13,['Talk-Show'],imdb_episode_images\Ykkösaamu.jpg
99102,tt0288359,The Frost Programme,NaN,NaN,NaN,NaN,1977-06-02,['Talk-Show'],NaN
99103,tt11994996,The Fake Spaniards Show,The Fake Spaniards are a group of characters k...,NaN,NaN,NaN,2010-11-23,['Comedy'],imdb_episode_images\The_Fake_Spaniards_Show.jpg

In [12]:
df["Slug"].duplicated().sum()

np.int64(25)

In [13]:
df = df[~df["Slug"].duplicated()]
df

,Slug,Title,Description,Rating,Rating Count,Duration,Release Date,Genres,Poster
0,tt0035599,Voice of Firestone Televues,Documentary films on diverse subjects.,NaN,NaN,NaN,1943-11-29,NaN,NaN
1,tt15340888,Lady Napoleon,"Sophie, descendant of Napoleon, leads Lady Nap...",NaN,NaN,NaN,NaN,"['Animation', 'Action', 'Adventure']",imdb_episode_images\Lady_Napoleon.jpg
2,tt27658590,MañanaEsTooLate con Lorenzo Parro,A comedy show that serves up the funniest and ...,NaN,NaN,NaN,2020-04-07,['Comedy'],imdb_episode_images\MañanaEsTooLate_con_Lorenz...
3,tt10515284,D_Sawz Tv,NaN,NaN,NaN,NaN,2016-09-03,['Comedy'],imdb_episode_images\D_Sawz_Tv.jpg
4,tt4816058,Dragons: Race to the Edge,Unlock the secrets of the Dragon Eye and come ...,8.2,9308.0,NaN,2015-06-26,"['Animation', 'Action', 'Adventure']",imdb_episode_images\Dragons_Race_to_the_Edge.jpg
...,...,...,...,...,...,...,...,...,...
99097,tt6403100,Everest Rescue,Rescue pilots in the Himalayas battle altitude...,8.4,81.0,NaN,2017-01-08,['Reality-TV'],imdb_episode_images\Everest_Rescue.jpg
99098,tt11994064,Antartida,5.4 million square miles. -76 degrees Fahrenhe...,7.5,12.0,NaN,2021-04-01,['Adventure'],imdb_episode_images\Antartida.jpg
99101,tt11994256,Ykkösaamu,The &quot;sister show&quot; of the radio progr...,4.4,9.0,NaN,2008-09-13,['Talk-Show'],imdb_episode_images\Ykkösaamu.jpg
99102,tt0288359,The Frost Programme,NaN,NaN,NaN,NaN,1977-06-02,['Talk-Show'],NaN
99103,tt11994996,The Fake Spaniards Show,The Fake Spaniards are a group of characters k...,NaN,NaN,NaN,2010-11-23,['Comedy'],imdb_episode_images\The_Fake_Spaniards_Show.jpg

In [14]:
# Save back to the CSV file
df.to_csv(f"modified_{targetCSV}", index=False)